version: '2.0'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=grouper

  web:
    build: .
    container_name: grouper
    command: "daphne grouper.asgi:application -b 0.0.0.0 -p 8080"
    expose:
      - "8080"
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - redis
    environment:
      - SECRET_KEY=some_secret_key
      - AWS_ACCESS_KEY_ID=aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=aws_secret_access_key
      - AWS_STORAGE_BUCKET_NAME=aws_storage_bucket_name
      - AWS_S3_CUSTOM_DOMAIN=aws_custom_domain

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web


volumes:
  postgres_data: