version: '2.0'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=grouper

  web:
    build: .
    container_name: grouper
    command: "daphne grouper.asgi:application -b 0.0.0.0 -p 8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - redis
    env_file:
      - docker.env

  redis:
    image: redis:5
    ports:
      - "6379:6379"


volumes:
  postgres_data: